config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :clocks, only: [:new, :create, :index]

  root 'clocks#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clock.rb
class Clock < ApplicationRecord
  validates :user, :in_out, :time, presence: true
  validates :in_out, inclusion: { in: ['In', 'Out'] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController

  def index
    @clocks = Clock.all
  end

  def new
    @clock = Clock.new
  end

  def create
    @clock = Clock.new(clocks_params)
    @clock.time = Time.now.localtime
    if @clock.save
      flash[:notice] = "You clocked #{@clock.in_out.downcase} successfully"
      redirect_to new_clock_path
    else
      render 'new'
    end
  end

  private

  def clocks_params
    params.require(:clock).permit(:user, :in_out, :time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clocks_helper.rb
module ClocksHelper
end

app/views/clocks/index.html.erb
<main class='grid-container'>
  <h1>All Events</h1>
  <table>
    <tr>
      <th>User</th>
      <th>In/Out</th>
      <th>Time</th>
    </tr>
    <% @clocks.each do |clock| %>
    <tr>
      <td><%= clock.user %></td>
      <td><%= clock.in_out %></td>
      <td><%= clock.time.strftime("%F at %I:%M%p") %></td>
    </tr>
    <% end %>
  </table>

  <%= link_to 'Log new time', new_clock_path %>
</main>

app/views/clocks/new.html.erb
<main class='grid-container'>
  <h1>Punchclock</h1>
  <section>
    <h2>Date: <%= Date.today %></h2>
  </section>
  <section>
    <h3>Time is:</h3>
    <time id='currentTime' class='currentTime'></time>
  </section>

  <%= form_with model: @clock, local: true do |form| %>
  <% if @clock.errors.any? %>
   <div id='error_explanation'>
     <h2>
       <%= pluralize(@clock.errors.count, 'error') %> prohibited
       this log from being saved:
     </h2>
     <ul>
       <% @clock.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
   <p>
     <%= form.label :user, 'Name' %>
     <%= form.text_field :user %>
   </p>
   <p>
     <%= form.label :in_out, 'In/Out' %>
     <%= form.select :in_out, options_for_select([['In','In'], ['Out', 'Out']])  %>
   </p>
   <p>
     <%= form.submit 'Log time' %>
   </p>
  <% end %>
  <%= link_to 'See all logs', clocks_path %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClockInOut</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class='notice'><%= flash[:notice] %></div>
    <%= yield %>
  </body>
</html>